apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: secret-nodejs
    name: secret-nodejs
  spec: {}
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: secret-nodejs
    name: secret-nodejs
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: secret-nodejs:latest
    postCommit: {}
    resources: {}
    source:
      git:
        uri: https://github.com/wael2000/secret-nodejs.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: nodejs:4
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: zwY1MV2BlhjqGlJpulrF
      type: GitHub
    - generic:
        secret: 7OggXSoJNtMoztXsT3dL
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: secret-nodejs
    name: secret-nodejs
  spec:
    replicas: 1
    selector:
      app: secret-nodejs
      deploymentconfig: secret-nodejs
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/container.secret-nodejs.image.entrypoint: '["container-entrypoint","/bin/sh","-c","$STI_SCRIPTS_PATH/usage"]'
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: secret-nodejs
          deploymentconfig: secret-nodejs
      spec:
        containers:
        - image: secret-nodejs:latest
          name: secret-nodejs
          ports:
          - containerPort: 8080
            protocol: TCP
          env:
          - name: COUNTRY
            value: UAE
          - name: LANGUAGE
            value: ar
          -
            name: USERNAME
            valueFrom:
              secretKeyRef:
                key: username
                name: mysecret
          -
            name: PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: mysecret
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - secret-nodejs
        from:
          kind: ImageStreamTag
          name: secret-nodejs:latest
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: secret-nodejs
    name: secret-nodejs
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: secret-nodejs
      deploymentconfig: secret-nodejs
  status:
    loadBalancer: {}
kind: List
metadata: {}
